### ISSUE TITLE
Connect portion of converted network to another network?

### ISSUE THREAD

**Issue by ashwinnair14** [ethereon/caffe-tensorflow#20]
Hi,
I would like to know If it is possible to use the output of a certain stage of converted  network as an input to another network ?
Which can then be trained and saved.
For Eg. I would like to use reproduce paper http://arxiv.org/abs/1411.4389 .
As the input I use their given singleframe_RGB model given in http://www.eecs.berkeley.edu/~lisa_anne/LRCN_video_weights.html .

**Comment by ethereon** [comment]
Sure, you can alter/adapt the network any way you want after the conversion - it's just a regular tensorflow graph.

**Comment by AhmadRa** [comment]
Hey, would you please elaborate on this or post a link on further reference ?

**Comment by ethereon** [comment]
After conversion, there are no more Caffe dependencies (or caffe-tensorflow dependencies, excluding the thin convenience wrapper).

Since this isn't particularly related to caffe-tensorflow, I'd recommend asking in one of the tensorflow usergroups (eg: [TensorFlow's stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow))
