### ISSUE TITLE
Padding always set to SAME

### ISSUE THREAD

**Issue by petewarden** [ethereon/caffe-tensorflow#3]
First, thanks for putting this together, it's great to see!

I just wanted to add a note that for future work, I've found the padding on convolution and maxpool layers the hardest thing to translate over, since both Caffe and TensorFlow have complex behaviors around the edges. I believe there are even some combinations in Caffe that can't currently be expressed in TensorFlow (since it only supports VALID and SAME).

Right now the translation always assumes SAME. If I get a chance I'll try to add in a warning during the translation process if the original network has other padding, and send a PR, but I wanted to add this as a comment in case anyone else runs into this issue.

Thanks again for this project.

**Comment by ethereon** [comment]
Thanks for the note. I've added a reference to this issue in the readme.

**Comment by ethereon** [comment]
The new version auto-detects `SAME` / `VALID` padding modes (tested on GoogLeNet), and throws an exception if it cannot be translated to TensorFlow.

For posterity: while this fixes the padding issues, similar concerns remain for other parameters which are either currently not translated by this implementation, or cannot be translated because of limitations in TensorFlow.

**Comment by parth1595** [comment]
@petewarden @ethereon 
I have been also getting the same problem while converting caffe model to tensorflow. I have also try tf.pad api before applying convolution to get the proper output shape but it gives me different activation values at convolution output.

Is there any solution to overcome this issue ?
